apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kc025gl1b-python
  janus-idp.io/tekton: kc025gl1b-python
  backstage.io/kubernetes-id: kc025gl1b-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: kc025gl1b-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
