apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: kc025gl1b-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:901bb950c47f9171270a1aa1f9cb39f46bfb2eb1@sha256:0f3a368449017239827bfe84122d6dc8e05e5e437759981fdfff7010a215d9a9
          name: container-image
